version: '3'
services:
  postgres_sql:
    container_name: whatsapp_clone_sql
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: whatsapp_clone
      POSTGRES_PASSWORD: whatsapp_clone
    ports:
      - "5432:5432"
    volumes:
      - sbt-pg-dataset:/var/lib/postgresql/data
    command: >
      bash -c "
        /usr/local/bin/docker-entrypoint.sh postgres -c 'log_statement=all' &
        sleep 10
        psql -U whatsapp_clone -c 'CREATE DATABASE whatsapp_clone;'
        wait
      "

  pgadmin:
    container_name: sbt-pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

volumes:
  sbt-pg-dataset:
